### ISSUE TITLE
Error in siber$sample.sizes[i, j] : subscript out of bounds

### ISSUE THREAD

**Issue by VirginiaMorera** [AndrewLJackson/SIBER#10]
Hi. I am trying the new stand-alone SIBER version, with RStudio version 0.99.486, R version 3.2.2. 
I have formatted my data to match the example data provided with the package, but instead of three groups for each community I have 6. Using the exact same code as in the vignette, everything runs fine until I try to plot the ellipses. The data is plotted correctly (I think) but it only plots two ellipses, as seen in the picture, and an error message appears: "Error in siber$sample.sizes[i, j] : subscript out of bounds" 

![siber_error](https://cloud.githubusercontent.com/assets/11058769/10845823/72615d08-7f0b-11e5-9394-f26ce751d1c5.png)

I thought this might happen because there's a limit of groups for each community, but I subsetted the data so I only had 3 groups per community, and the same error appeared. I can provide an example of the kind of data I am using if necessary, but it's carbon and nitrogen isotopic signatures, so nothing weird about that... 

Any ideas on what am I doing wrong?

Thank you.

**Comment by AndrewLJackson** [comment]
Hi Virginia

Quick guess: how many communities have you? It looks a bit like to plotting two ellipses, one for each of two communities. Have you got you groups and community ID columns right way around? Are your group/community ID codes sequential integers starting at 1? 

Best wishes
Andrew

**Comment by VirginiaMorera** [comment]
Woha, spot on! Columns were out of order, and group ID codes where numeric, not integer. All set now, thank you very much!

**Comment by AndrewLJackson** [comment]
excellent!

On 6 November 2015 at 12:10, VirginiaMorera <notifications@github.com>
wrote:

> Woha, spot on! Columns were out of order, and group ID codes where
> numeric, not integer. All set now, thank you very much!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndrewLJackson/SIBER/issues/10#issuecomment-154394646>
> .
>



-- 
*You can now follow SIAR on Facebook
<http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914>
or
try my video podcasts
<http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php> for
R

Dr Andrew Jackson
Associate Professor
School of Natural Sciences
Director of the Trinity Centre for Biodiversity Research
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex <https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php
