### ISSUE TITLE
probability that one groyp is larger than the other

### ISSUE THREAD

**Issue by BelindaCannell** [AndrewLJackson/SIBER#100]
Hi Andrew
when we do pairwise comparisons by calculating the proportion of SEAb that differed between 2 groups, to determine if one group is significantly larger than another, is it correct that the probability is analogous to a P values, and hence anything >=0.95 indicates that one group is statistically signficantly larger than the other?
Kind regards
Belinda

**Comment by AndrewLJackson** [comment]
Hi Belinda

Sort of but not really is the pretty unhelpful answer. Fundamentally these are very different concepts as outlined here https://stats.stackexchange.com/questions/341553/what-is-bayesian-posterior-probability-and-how-is-it-different-to-just-using-a-p#:~:text=The%20fundamental%20difference%20between%20a,belief%20of%20a%20particular%20parameter. Ultimately there is no accepted threshold for a Bayesian probability unlike the arbitrary and often discussed p<0.05. Its better it think to focus on effect size and how meaningful the difference is as much as wanting a probability value that is low when testing for dissimilarities.

Best wishes
Andrew

--
Prof Andrew Jackson, PhD, FTCD
Director Biology and Biomedical Sciences TR060
Professor in Zoology
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.
***@***.******@***.***>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/



From: BelindaCannell ***@***.***>
Date: Thursday, 28 September 2023 at 09:15
To: AndrewLJackson/SIBER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AndrewLJackson/SIBER] probability that one groyp is larger than the other (Issue #100)

Hi Andrew
when we do pairwise comparisons by calculating the proportion of SEAb that differed between 2 groups, to determine if one group is significantly larger than another, is it correct that the probability is analogous to a P values, and hence anything >=0.95 indicates that one group is statistically signficantly larger than the other?
Kind regards
Belinda

**Comment by BelindaCannell** [comment]
Hi Andrew
Thanks for your response.

My confusion has arisen, as in a paper by Reid et al 2016, they reported no difference between trophic niches for pairwise comparisons in SEAB with probabilities ranging from 0.56- 0.83.

However, in some of my own results, the probability of the trophic niche in 2022 being wider than in 2021 was only 0.67, yet from the graphs below I would have thought that it was wider??

[A graph of different types of ellipses  Description automatically generated]

[A diagram of a diagram of a complex circle  Description automatically generated with medium confidence]


Can you advise if I have interpreted this incorrectly?

Also, how do I determine the effect size you mentioned?

Kind regards
Belinda

Dr Belinda Cannell
Research Fellow
Tues-Fri
Oceans Institute/School of Biological Sciences  *  M470, Stirling Hwy, Crawley 6009 Australia
T +61 8 6488 7659  *  M +61 421 641 050  *  E ***@***.***
[The University of Western Australia]<https://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/uwa-logo>
[UWA on Facebook]<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/facebook> [UWA on Twitter] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/twitter>  [UWA on Youtube] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/youtube>  [UWA on Linked In] <http://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/linkedin>  [UWA on Instagram] <http://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/instagram>

**Comment by AndrewLJackson** [comment]
Hi Belinda

I cant see those figures as they didn’t embed. Its kind of up to you what you want to argue constitutes a meaningful (aka significant) difference between two estimated parameters. This could involve consideration of the probability of them being different, and certainly values greater than 0.9 start to feel more meaningful that values around 0.6. But then there is also the effect size which is simply the magnitude of the difference. You can calculate a distribution of this effect size in a similar way to calculating the probability of one being larger than the other simply by subtracting the posterior draws from one of the ellipses from the other.

Best wishes
Andrew

--
Prof Andrew Jackson, PhD, FTCD
Director Biology and Biomedical Sciences TR060
Professor in Zoology
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.
***@***.******@***.***>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/



From: BelindaCannell ***@***.***>
Date: Friday, 29 September 2023 at 02:48
To: AndrewLJackson/SIBER ***@***.***>
Cc: Andrew Jackson ***@***.***>, Comment ***@***.***>
Subject: Re: [AndrewLJackson/SIBER] probability that one groyp is larger than the other (Issue #100)
Hi Andrew
Thanks for your response.

My confusion has arisen, as in a paper by Reid et al 2016, they reported no difference between trophic niches for pairwise comparisons in SEAB with probabilities ranging from 0.56- 0.83.

However, in some of my own results, the probability of the trophic niche in 2022 being wider than in 2021 was only 0.67, yet from the graphs below I would have thought that it was wider??

[A graph of different types of ellipses Description automatically generated]

[A diagram of a diagram of a complex circle Description automatically generated with medium confidence]


Can you advise if I have interpreted this incorrectly?

Also, how do I determine the effect size you mentioned?

Kind regards
Belinda

Dr Belinda Cannell
Research Fellow
Tues-Fri
Oceans Institute/School of Biological Sciences * M470, Stirling Hwy, Crawley 6009 Australia
T +61 8 6488 7659 * M +61 421 641 050 * E ***@***.***
[The University of Western Australia]<https://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/uwa-logo>
[UWA on Facebook]<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/facebook> [UWA on Twitter] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/twitter> [UWA on Youtube] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/youtube> [UWA on Linked In] <http://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/linkedin> [UWA on Instagram] <http://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/instagram>

**Comment by BelindaCannell** [comment]
Hi Andrew
Thanks so much for your prompt responses.

Cheers
Belinda

Dr Belinda Cannell
Research Fellow
Tues-Fri
Oceans Institute/School of Biological Sciences  *  M470, Stirling Hwy, Crawley 6009 Australia
T +61 8 6488 7659  *  M +61 421 641 050  *  E ***@***.***
[The University of Western Australia]<https://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/uwa-logo>
[UWA on Facebook]<http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/facebook> [UWA on Twitter] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/twitter>  [UWA on Youtube] <http://www.uwa.edu.au/university-campaigns-resources/emailsig2015/youtube>  [UWA on Linked In] <http://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/linkedin>  [UWA on Instagram] <http://www.web.uwa.edu.au/university-campaigns-resources/emailsig2015/instagram>
