### ISSUE TITLE
How many populations can I compare at one time?

### ISSUE THREAD

**Issue by kzd0007** [AndrewLJackson/SIBER#102]
I'm getting error code: Error in eigen(sigma/c.scale) : infinite or missing values in 'x'

when I try to do SEA for more than 4 groups in a single community. Is 4 the limit?

**Comment by AndrewLJackson** [comment]
Hi
No there should not be a limit. Do all of your groups have at lease 3 distinct data points? Which would be the absolute minimum to calculate the ellipse statistics?
Best wishes
Andrew


––––––––––––

Dr Andrew Jackson, PhD, FTCD
Professor in Zoology
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

***@***.***
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

________________________________
From: kzd0007 ***@***.***>
Sent: Monday, March 4, 2024 6:17:34 PM
To: AndrewLJackson/SIBER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AndrewLJackson/SIBER] How many populations can I compare at one time? (Issue #102)


I'm getting error code: Error in eigen(sigma/c.scale) : infinite or missing values in 'x'

when I try to do SEA for more than 4 groups in a single community. Is 4 the limit?

**Comment by kzd0007** [comment]
Wow that's embarrassing--yep that was it! Sometimes even with less than 3 you can force it to do the ellipse (don't worry I haven't tried to publish anything with data like that--I've just done it while playing with preliminary results for things) but this data set had multiple groups with less than 3 and it did not like that. 

Thank you so much!!
