### ISSUE TITLE
Trouble with SIBER SEAb parameters

### ISSUE THREAD

**Issue by ziegler57** [AndrewLJackson/SIBER#104]
@AndrewLJackson 
I am working with Carbon Oxygen data of various species (group) grouped into two communities and I am having trouble with one of the features of SIBER:

1. When trying to set up and run the Bayesian ellipse SEAb, I run into an error: 
Using these parameters 
> parms <- list()
> parms$n.iter <- 2 * 10^4
> parms$n.burnin <- 1 * 10^3
> parms$n.thin <- 10
> parms$n.chains <- 2
> 
> priors <- list()
> priors$R <- 1 * diag(2)
> priors$k <- 2
> priors$tau.mu <- 1.0E-3
> 
> ellipses.posterior <- siberMVN(siber.z.example, parms, priors)

Error: .onLoad failed in loadNamespace() for 'rjags', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/mziegler/Library/R/x86_64/4.2/library/rjags/libs/rjags.so':
  dlopen(/Users/mziegler/Library/R/x86_64/4.2/library/rjags/libs/rjags.so, 0x000A): Library not loaded: /usr/local/lib/libjags.4.dylib
  Referenced from: <EBADECB5-DF43-3965-829D-81288CCF431B> /Users/mziegler/Library/R/x86_64/4.2/library/rjags/libs/rjags.so
  Reason: tried: '/usr/local/lib/libjags.4.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libjags.4.dylib' (no such file), '/usr/local/lib/libjags.4.dylib' (no such file), '/usr/lib/libjags.4.dylib' (no such file, not in dyld cache)

Is there something simple I am missing here? Any advice would be greatly appreciated!

**Comment by AndrewLJackson** [comment]
hi
it sounds like do not have JAGS installed or it is not installed correctly. I will add a note to the main README to help with this in future. https://mcmc-jags.sourceforge.io

**Comment by ziegler57** [comment]
Hi Andrew, thank you for your speedy response. I knew it was probably something small I was missing, thank you for steering me right. I'll install JAGS and look to the README for guidance.
