### ISSUE TITLE
Comparisons of Layman metrics between communities

### ISSUE THREAD

**Issue by noeliagobel** [AndrewLJackson/SIBER#105]
Hello, 

I am currently working on comparing Layman metrics and ellipses between pond food webs (with insects, fish, amphibians, etc) situated in different land use scenarios. My aim is to compare these metrics between land uses, so the ponds are situated in different land use conditions. I have three distinct types of land use, with seven ponds sampled in each land use scenario. To conduct these comparisons within a Bayesian framework, I am using SIBER. In my analysis, I consider that the land use type is my "community", but I  am a bit confused on how to use the "group" term. Given my objective of comparing whole food webs, should I define 'group' as the species identity regardless of each pond  identity?. Do you think Is this approach correct? My main concern is how to correctly represent the identity of each pond in the model... Would you please help me by providing some guidance on this?

Thank you very much,

Noelia Gobel

**Comment by benjaminhlina** [comment]
I would use species as the  `group` term for your analysis. I recently published a package [{nichetools}](https://benjaminhlina.github.io/nichetools/index.html) that provides additional functions and workflows to working with`{SIBER}` and `{nicheROVER}` that might be helpful to you and your analysis - Cheers, Ben

**Comment by noeliagobel** [comment]
Thank you for your response! I'll proceed by using species as the group term in my analysis. I'll also take a look at {nichetools} package—it sounds like it could be very helpful for my work.

**Comment by benjaminhlina** [comment]
You can close the the issue
