### ISSUE TITLE
pairwise ellipsesOverlap

### ISSUE THREAD

**Issue by gccardozo-ferreira** [AndrewLJackson/SIBER#108]
When calculating the proportion of the non-overlapping area of the two ellipses (prop.95.over) using the 'maxLikOverlap' function, is it possible to create an automated pairwise to compare between multiple ellipses without having to calculate each pair at once?

A good example of something similar is in the function 'overlap' from 'nicheROVER' package (Swanson et al., 2015).

**Comment by benjaminhlina** [comment]
You can use `{SIBER}` and a new package that is complementary to `{SIBER}` and `{nicheROVER}` called [{nichetools}](https://benjaminhlina.github.io/nichetools/) to do exactly what you're looking to do. Follow both the vignette in `{SIBER}` and the the vignette in `{nichetools}` to see how to do this.

**Comment by gccardozo-ferreira** [comment]
Hi Benjamin,

Thanks for your answer. I found it just before seeing your answer! I've cracked it before with {nicheROVER} and will now give a try with {SIBER}. I hope getting back to you is okay if I get stuck somewhere.

**Comment by benjaminhlina** [comment]
Glad to hear you found things and sure, what I suggest is closing this issue considering it is resolved and if you have issues/questions you can create an issue over on {nichetools} repo.

**Comment by gccardozo-ferreira** [comment]
Perfect, Benjamin! Thanks!
