### ISSUE TITLE
problem creating df_mu object

### ISSUE THREAD

**Issue by gccardozo-ferreira** [AndrewLJackson/SIBER#109]
Hi Benjamin,

Unfortunately, I'm encountering an error. While extracting the posterior distribution for μ and Σ, I cannot generate the object 'df_mu' because it always comes back with the following: 
Error in extract_mu(ellipses_posterior, pkg = "SIBER", data_format = "wide",  : 
  argumento não utilizado (community_df = cg_names)

I double-checked everything. It seems okay. The only thing I changed in the code was replacing the data name from your example with my data. Everything went smoothly so far.

Interestingly, the 'help' page in the package doesn't have this line 'community_df = cg_names'. See:
extract_mu(
  data,
  pkg = NULL,
  isotope_a = NULL,
  isotope_b = NULL,
  data_format = NULL
)

However, if I remove it, I'm able to create the 'df_mu' object but can't plot in the next step because it returns the following error:

Error in `combine_vars()`:
! At least one layer must contain all faceting variables: `community_name`
✖ Plot is missing `community_name`
✖ Layer 1 is missing `community_name`
✖ Layer 2 is missing `community_name`
Run `rlang::last_trace()` to see where the error occurred.

I tried different workarounds but couldn't find a solution.

**Comment by benjaminhlina** [comment]
Close this issue and open an issue with your error message and a reproducible example ([reprex](https://reprex.tidyverse.org/)) over on {[nichetools](https://github.com/benjaminhlina/nichetools)}.

**Comment by gccardozo-ferreira** [comment]
Will do, Benjamin! Thanks!
