### ISSUE TITLE
ellipse colors

### ISSUE THREAD

**Issue by AndrewLJackson** [AndrewLJackson/SIBER#11]
colors for ellipses need to be set using the palette function.

e.g. 

library('viridis')
palette(viridis(5))

or for full custom control of colour order...

palette(c("orange","blue","red","black","magenta","peachpuff"))

there is no code to fix, just update the vignette

**Comment by akbreezo** [comment]
Is it possible to add a legend and change group/community shapes?

**Comment by AndrewLJackson** [comment]
hi

you can add a legend manually using the function legend()

the easiest way to specify your own plotting points is to plot your raw
data yourself using

plot(my.x.data, my.y,data)

and customise your point and line colour choice by following the concepts
covered in my Scatter Plot podcast available at
http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php

you can then use the functions plotGroupEllipses() plotCommunityHulls()
plotGroupHulls() to add the various SIBER specific plots on top of the raw
plot of the data you have already created.

best wishes

andrew



On 12 February 2016 at 00:52, akbreezo <notifications@github.com> wrote:

> Is it possible to add a legend and change group/community shapes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndrewLJackson/SIBER/issues/11#issuecomment-183133115>
> .
>



-- 
*You can now follow SIAR
<http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914>
on Facebook or try my video podcasts
<http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php> for
R

Dr Andrew Jackson
Associate Professor
School of Natural Sciences
Director of the Trinity Centre for Biodiversity Research
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex <https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

**Comment by akbreezo** [comment]
Worked like a charm. Thank you!
