### ISSUE TITLE
Ideally would allow custom defined column headers in raw data

### ISSUE THREAD

**Issue by AndrewLJackson** [AndrewLJackson/SIBER#15]

**Comment by HarriPettittWade** [comment]
Hi Andrew,
Prior to the most recent update to SIBER 2.0 I was able to have additional column headers in my raw data sheet. i.e. in addition to iso1, iso2, group, community I had 'site' and 'species' as a reference. Now when I try to import the same data sheets the package no longer likes the extra headers and an error message pops up.

Is it essential there only be 4 column headers? 
Or can we revert back to having as many as we want, as long as the first 4 are iso1, iso2, group, community?

many thanks,
Harri

**Comment by AndrewLJackson** [comment]
hi harri

I'm pretty sure you can only have the four in the dataset that you pass to
SIBER

best wishes

andrew

On 14 February 2016 at 14:39, Harri Pettitt-Wade <notifications@github.com>
wrote:

> Hi Andrew,
> Prior to the most recent update to SIBER 2.0 I was able to have additional
> column headers in my raw data sheet. i.e. in addition to iso1, iso2, group,
> community I had 'site' and 'species' as a reference. Now when I try to
> import the same data sheets the package no longer likes the extra headers
> and an error message pops up.
>
> Is it essential there only be 4 column headers?
> Or can we revert back to having as many as we want, as long as the first 4
> are iso1, iso2, group, community?
>
> many thanks,
> Harri
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndrewLJackson/SIBER/issues/15#issuecomment-183901983>
> .
>



-- 
*You can now follow SIAR
<http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914>
on Facebook or try my video podcasts
<http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php> for
R

Dr Andrew Jackson
Associate Professor
School of Natural Sciences
Director of the Trinity Centre for Biodiversity Research
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex <https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php
