### ISSUE TITLE
Suggestion regarding group.names in createSiberObject

### ISSUE THREAD

**Issue by marknovak** [AndrewLJackson/SIBER#23]
Hi Andrew,
Super minor suggestion to add
`x<-x[order(x$community,x$group),]`
(or something like it) near the top of createSiberObject so that all $group.names have the same factor level ordering.
-mark

**Comment by AndrewLJackson** [comment]
great suggestion, thanks. I will flag this and implement something in the next release. thanks also for the code suggestion. Makes life much easier!

**Comment by AndrewLJackson** [comment]
this will be dealt with in a major update as I move to tidyverse implementation throughout SIBER.
