### ISSUE TITLE
Changing scales of axes in SIBER plots

### ISSUE THREAD

**Issue by kabrantes** [AndrewLJackson/SIBER#25]
Hi Andrew,

I was wondering how/if I can change the limits of the two axes to specified values. I want to have a couple of SEA plots with the same d13C & d15N scales for visual comparability, but can't find a way to do that. I tried... sorry if it is a very basic question.

Thank you!!!

**Comment by AndrewLJackson** [comment]
hi

its not an easy feature in SIBER. If you want custom plots you need to do some extra work. A worked example is included here https://cran.r-project.org/web/packages/SIBER/vignettes/Customising-Plots-Manually.html
