### ISSUE TITLE
Convergence plots

### ISSUE THREAD

**Issue by LaurieMaynard** [AndrewLJackson/SIBER#26]
Hi,
I was trying to look at the diagostic plots of my models (more specifically the convergence plots of MCMC). I was wondering if there was a quick way to do so with SIBER. 

Thanks,

**Comment by AndrewLJackson** [comment]
hi,
I haven't made this easy to do. In hindsight I wish I had coded SIBER very differently and preserved the mcmc coda outputs from jags to enable such convergence checking. In the meantime, I will simply store the raw coda object in a separate place to keep memory demand down, but it will take me probably a few weeks to implement this.

**Comment by AndrewLJackson** [comment]
Im looking at it now, and unhelpfully, I didnt even preserve the multiple chain runs when creating the estimates of SEA etc... so I can't even do some basic "hairy caterpillar" plots. I will fix this ASAP

**Comment by AndrewLJackson** [comment]
hi. Latest development version includes a new vignette showing you how you can now save the raw jags files and use standard convergence diagnostics on each ellipse https://github.com/AndrewLJackson/SIBER

thanks for prompting this improvement. It was long overdue.

 devtools::install_github("andrewljackson/SIBER@master",
  build_vingettes = TRUE)
  library(SIBER)

**Comment by Sittelle** [comment]
Thank you very much!
