### ISSUE TITLE
SEAb is distinct from SEA and SEAc

### ISSUE THREAD

**Issue by palomapali** [AndrewLJackson/SIBER#28]
The SEAb from my data really differs from the SEA and SEAc. I already run more chains, but the problem seems to persist. Is there anyway to solve this problem?

![image](https://cloud.githubusercontent.com/assets/27308045/26066168/ab37005e-395b-11e7-80f7-0af23b2b6e3e.png)

**Comment by AndrewLJackson** [comment]
Are you using the new package SIBER or the old package siar?

**Comment by palomapali** [comment]
Hi Andrew,

I am using the new released SIBER.

**Comment by AndrewLJackson** [comment]
i will take a look. Actually i think someone else flagged some similar behaviour. Im not sure what is causing this. It might take me a few days

**Comment by palomapali** [comment]
Ok, thanks!

**Comment by AndrewLJackson** [comment]
hi, please could you email me some code and some data so I can replicate this and investigate?

**Comment by palomapali** [comment]
Sure. See attached.

2017-06-01 4:29 GMT-05:00 Andrew Jackson <notifications@github.com>:

**Comment by AndrewLJackson** [comment]
hi again

did i ever get back to you about this? Im not sure the attahcemnets are working on GitHub. could you email me directly please if this issue is still on-going?

cheers
andrew

**Comment by AndrewLJackson** [comment]
also, what are the sample sizes for each of your groups?

**Comment by palomapali** [comment]
Hi Andrew,

I was away in the field for the summer and trying to catch with everything.
I did send you the data as requested and still not sure what is the problem.

Cheers,
Paloma

2017-08-14 6:42 GMT-05:00 Andrew Jackson <notifications@github.com>:

**Comment by BelindaCannell** [comment]
I found a similar issue but worked out that if I had all my data ordered by community and then by group that this issue resolved.
Cheers
Belinda
