### ISSUE TITLE
Non parametric data

### ISSUE THREAD

**Issue by Catalinama** [AndrewLJackson/SIBER#29]
Hi,
Carbon isotopes of my data are non normally distributed. I have tried several transformation (log, log (sqr), arsin), without any success.
I would like to use Stable Isotope Baysesian Ellipses in R. What would you suggest?
Thanks in advance

**Comment by AndrewLJackson** [comment]
hi

sorry for the delay in replying. in short I dont have any suggestion. Consider though that some tests for normality are overly punitive, especially for small sample sizes, and you may be happy to proceed on the assumption of normality even if the data fails the test

best wishes

andrew
--
––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 21 Jul 2017, at 14:18, Catalinama <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Carbon isotopes of my data are non normally distributed. I have tried several transformation (log, log (sqr), arsin), without any success.
I would like to use Stable Isotope Baysesian Ellipses in R. What would you suggest?
Thanks in advance
