### ISSUE TITLE
Adjusting point size in 'PlotSiberObject'

### ISSUE THREAD

**Issue by HendrikSchultz** [AndrewLJackson/SIBER#31]
Hi Andrew,

I am plotting a siber object using "plotSiberObject" and have trouble adjusting the point size. Changing the line "cex = 0.5" to other values does not have an effect. Please let me know if there is a mistake in the code below.

plotSiberObject(skua_siber,
                ax.pad = 0.5, #padding applied around the extremes of the data.
                hulls = F, community.hulls.args, 
                ellipses = F, group.ellipses.args,
                group.hulls = F, group.hull.args,
                bty = "L",
                iso.order = c(1,2),
                xlab = expression({delta}^13*C~'\u2030'),
                ylab = expression({delta}^15*N~'\u2030'),
                points.order= c(1,0),
                cex = 2.9
                
)

Many thanks in advance for your help - please keep up the excellent work on your packages!

Hendrik

**Comment by AndrewLJackson** [comment]
hi hendrik

those built in plotting functions are not fully customisable: they are only really intended for quick plots. The vignette “customising plots manually” illustrates how you can take full control over the plotting.

ive also attached a script file to illustrate custom plotting using ggplot if you prefer that approach.

best wishes

andrew


––––––––––––
Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 24 Jan 2018, at 22:51, HendrikSchultz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Andrew,

I am plotting a siber object using "plotSiberObject" and have trouble adjusting the point size. Changing the line "cex = 0.5" to other values does not have an effect. Please let me know if there is a mistake in the code below.

plotSiberObject(skua_siber,
ax.pad = 0.5, #padding applied around the extremes of the data.
hulls = F, community.hulls.args,
ellipses = F, group.ellipses.args,
group.hulls = F, group.hull.args,
bty = "L",
iso.order = c(1,2),
xlab = expression({delta}^13C~'\u2030'),
ylab = expression({delta}^15N~'\u2030'),
points.order= c(1,0),
cex = 2.9

)

Many thanks in advance for your help - please keep up the excellent work on your packages!

Hendrik

**Comment by HendrikSchultz** [comment]
Thanks for that Andrew, I found your ggplot code in the vignette, much appreciated! :-)

Many thanks and all the best!

Hendrik
