### ISSUE TITLE
probability SEA-B output

### ISSUE THREAD

**Issue by veronicar239** [AndrewLJackson/SIBER#46]
Hi Andrew,

I wanted to follow up on something we chatted about at IsoEcol. I am interested to compare SEA-B between groups (test the factor 'year'). You mentioned that you had written code to calculate the probability of SEA-B, which could then be used to compare SEA-B output between groups? I looked through the vignettes for it but haven't found it - any chance you have this somewhere else?

Thanks!

Cheers,
Veronica

**Comment by AndrewLJackson** [comment]
hi Veronica
sorry this is quite late. some code examples here https://github.com/andrewcparnell/simms_course/blob/master/aj-content/practicals/siber-comparing-populations.Rmd
