### ISSUE TITLE
Problems running the code for test of convergence of Bayesian Inference

### ISSUE THREAD

**Issue by VanessaDS** [AndrewLJackson/SIBER#47]
Hi Andrew,

I'm trying to use one of your latest vignettes regarding the test of convergence for BI. 
I've it very helpfull however, I can't run the code neither with my data nor with the demo file. 
The issue is that when I give parms$output = TRUE to R it seems that it doesn't save anything although I've set the working directory. As a consequence (I think), my object containing the models is empty.
I'm not really good with R so probably is something that I'm missing, I hope you can help.

Thanks 

Vanessa

**Comment by AndrewLJackson** [comment]
hi Vanessa
this works fine for me. I first set up an RStudio project or simply set the working directory to somewhere I want to use then change line 32 to `parms$save.dir = getwd()` of that vignette. I then get 6 .Rdata files and the rest of the code that does the convergence testing works ok.
