### ISSUE TITLE
Colors in SIBER

### ISSUE THREAD

**Issue by melizaantunes** [AndrewLJackson/SIBER#48]
Hi Andrew,

I've been working with SIBER and I have some questions for you.

In my data, I have 4 groups and 2 communities, but I am having difficulties in knowing which color represents which group and community in my ellipses. Is there any tool in which I change or discover the colors?

Thanks a lot.

Maria

**Comment by bicudose** [comment]
I have the same isue.

**Comment by melizaantunes** [comment]
me too

I can not find a caption or command that tells me the colors of the ellipses

**Comment by AndrewLJackson** [comment]
it might be easier to track this using ggplot. see this gist example https://gist.github.com/AndrewLJackson/b16fb216d8a9a96c20a4a979ec97e7b0

**Comment by bicudose** [comment]
Thank you so much. You save my day. 

Thiago.

**Comment by melizaantunes** [comment]
Thanks a lot!!!
