### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by melizaantunes** [AndrewLJackson/SIBER#51]
Hello, I'm having some problems in identifying which geometric shape of my graph corresponds to which community of my data
Is there any function or code I can use for this?

Thank you very much

Maria

**Comment by AndrewLJackson** [comment]
you should be able to work it out from the community.group coding e.g. 2.1 is community 2, group 1, and the corresponding order of your points and colour palettes. Or you can work it out from the means of each of your groups. Or you could plot it via ggplot2 which does make the link between the groups more obvious. See the FAQs for a link https://github.com/AndrewLJackson/SIBER
