### ISSUE TITLE
Laymann metrics

### ISSUE THREAD

**Issue by melizaantunes** [AndrewLJackson/SIBER#54]
Hello Andrew, I have a question about SIBER

In the generated graph of the Laymann metrics, is it possible to plot the metrics of two communities in the same figure? I'm not getting

Thank you in advance

**Comment by AndrewLJackson** [comment]
yes but customised plotting of data or results requires coding outside SIBER's functionality. Some examples here are provided as a starting point. https://github.com/andrewcparnell/simms_course/blob/master/aj-content/practicals/siber-comparing-communities.Rmd
