### ISSUE TITLE
Issues with the SIBER introduction's script

### ISSUE THREAD

**Issue by GuillaumeBridier** [AndrewLJackson/SIBER#56]
Hi all!

I have tried to realized the statistical analyses described in the "Introduction to SIBER" script (https://cran.r-project.org/web/packages/SIBER/vignettes/Introduction-to-SIBER.html) on my own data but the analyses don't seems to work.

I would like to compare some Layman metrics between two communities (site1 & site2). I have thus used these function provided by the SIBER package:
laymanMetrics(isotopes[isotopes$community=="site1",1],isotopes[isotopes$community=="site1",2])
laymanMetrics(isotopes[isotopes$community=="site2",1],isotopes[isotopes$community=="site2",2])
I have created a siberobject to use the Bayesian approach and split each communities in three groups (suspension feeders, deposit feeders and carnivores). All the laylan metrics generated by the bayesian approach give quite different results from the metrics provided by the laymanMetrics() function...

Has anyone ever had this issue before?

I was wondering if it could be due to the fact that I had to split each community in three distincts groups. I have tried to start again the same analysis with only one group (“benthos”) similar for both communities. Bayesian output for SEA give quite consistent results. However, the siberdensityplot function based on the Bayesian metrics doesn’t work… I have this error message:
“Error in hdrcde::hdr(dat[, j], probs, h = stats::bw.nrd0(dat[, j])) : 
  Insufficient data”

Does anyone know why?

Thank you very much for your help!!
All the best,

Guillaume

**Comment by jlpallard** [comment]
Hi Andrew,

I am getting the same error when I use my data, but only when I try to create plots for TA. The plots for dX_range and dY_range work fine.

Groups = streams (n=11)
Community = # of species in each stream (1, 2, or 3)

Any insight would be great!

Jacquie

![TA](https://user-images.githubusercontent.com/103222040/162478629-a411f062-627a-47df-ace4-741578e17435.jpeg)
![BMI](https://user-images.githubusercontent.com/103222040/162478639-9f187fc3-2845-41da-94b8-c7710aaf85b6.jpeg)
![TP](https://user-images.githubusercontent.com/103222040/162478699-50efdab7-915b-44f4-b746-0794343c0ffd.jpeg)

**Comment by fpasotti** [comment]
I am also having the same issue and it puzzles me since the Layman.B list is indeed made up of 4 lists with values 0 but it makes no sense since the ellipses are large enough for these communities (I have managed to calculate SEAB and SEAC no problem..
<img width="936" alt="Screenshot 2023-08-08 at 10 45 58" src="https://github.com/AndrewLJackson/SIBER/assets/51359033/c61ab2eb-d25a-4a0d-9a40-0af6ea4c44e5">
