### ISSUE TITLE
COMPARE ELLIPSES FOR SIGNIFICANT DIFFERENCE IN SEAb

### ISSUE THREAD

**Issue by emsa999** [AndrewLJackson/SIBER#58]
Hello!

I am using the latest version of SIBER to compare niche breadths of a species across different years using the Bayesian standard ellipse area. I have noticed the script for comparing SEA.b size (and getting a P value) between two groups (which was included in the script of the SIAR package) is no longer available in SIBER. Is there a way to perform this comparison or is there a reason why this has been removed in SIBER?

Thank you!

**Comment by fraser-combe** [comment]
I am interested in this topic above and could not find a resolution, would anyone be able to make any suggestions.  thanks

**Comment by AndrewLJackson** [comment]
hi. I don't remember why I removed it from the vignettes, but the code is available here https://github.com/andrewcparnell/simms_course/tree/master/aj-content/practicals in siber-comparing-populuations.Rmd or siber-comparing-communities.Rmd

**Comment by martinpache** [comment]
Hello Andrew
I can compare SEAB from different groups, as a proportion of simulations that are bigger or smaller related to total simulations.
But given the advantages of using SEAc corrected in small sample sizes, do you know how can i do to compare ellipses area but in the corrected form? there is an analogue of SEAB which is corrected to sample size (SEAc)?
Thanks so much
Martin

**Comment by AndrewLJackson** [comment]
Hi martin

As illustrated using simulations in the associated paper SEAB is a director comparator to SEAc

Best wishes
andrew

From: martinpache ***@***.***>
Date: Friday, 7 June 2024 at 20:30
To: AndrewLJackson/SIBER ***@***.***>
Cc: Andrew Jackson ***@***.***>, State change ***@***.***>
Subject: Re: [AndrewLJackson/SIBER] COMPARE ELLIPSES FOR SIGNIFICANT DIFFERENCE IN SEAb (#58)
[External Email] This email originated outside of Trinity College Dublin. Do not click links nor open attachments unless you recognise the sender and know the content is safe.

Hello Andrew
I can compare SEAB from different groups, as a proportion of simulations that are bigger or smaller related to total simulations.
But given the advantages of using SEAc corrected in small sample sizes, do you know how can i do to compare ellipses area but in the corrected form? there is an analogue of SEAB which is corrected to sample size (SEAc)?
Thanks so much
Martin
