### ISSUE TITLE
Calculating the point estimates of the 6 Layman metrics for an entire group of data.

### ISSUE THREAD

**Issue by bsharris381** [AndrewLJackson/SIBER#59]
Hi all,

I looked and didn't see my exact question posed here.  SIBER has been great to work with and this is an issue with me not being able to figure layman metrics for a group of data rather than a community (like mentioned in the vignette).  I have 6 groups and 2 communities.  I would like to produce community metrics for a single group for comparison purposes.

Appreciate any help!

Thanks,

Brandon

**Comment by AndrewLJackson** [comment]
﻿Hi Brandon

From the Intro To SIBER vignette:

library(SIBER)

# load in the included demonstration dataset
data("demo.siber.data")
#
# create the siber object
siber.example <- createSiberObject(demo.siber.data)

# Calculate summary statistics for each group: TA, SEA and SEAc

group.ML <- groupMetricsML(siber.example)

print(group.ML)

best wishes
Andrew
--
Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by bsharris381** [comment]
Hi Andrew,

Thanks for the prompt response, although I fear that I may have not done a good job describing my question.  I used the group metric function to calculate SEAc.  I’m interested in comparing species isotopic niches across two sections of a river (lower and upper) and then across two rivers.  I was thinking that the laymanmetrics function could be passed on a subset of the siber.example list and the result would be all the layman metrics for a single species (i.e., group) in the two river sections and both rivers.

I was trying to pull out what I needed from the original siber.example list.  As I write this, one thing that I didn’t try is to run a dataset that includes only one species.  The communities become river reaches for one river (comm .1 and 2) and then rive5 reaches for second river (comm. 3 and 4). By default, this would provide community metrics for a single species across the river reaches and rivers?

I think I answered my own question, well hopefully.  I will be test it out.

Thanks,

Brandon

**Comment by AndrewLJackson** [comment]
Hi

I think I understand now. See attached

Best wishes
Andrew

--
Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by bsharris381** [comment]
Hi Andrew,

Again thanks for responding!  Sorry for my delayed response.  I took a long weekend to visit family.

I didn’t see anything attached to your response like you mentioned.  Maybe I somehow overlooked it? Perhaps you forgot to include attachment?

My idea of using the groups and communities to calculate Layman metrics for a single species across river reaches and different rivers didn’t work.  I was a little confused between the usage of laymanMetric and CommunityMetricsML.  I can pass vectors for x and y data to laymanMetric that represent a single species in say 1 of 4 areas of interest (i.e., upper or lower river and either river one or rive two) and produce Layman metrics.  Under CommunityMetricsML, I would need to have >1 group for a community, but I can’t do that because I am interested in a single group within a community (i.e., a species).

Is there a faster way within SIBER…and one where my chance of making an error is reduced?  Mine would require a lot of separate csv files or to subset the full dataframe many times (e.g., each species and area of interest).

THANKS!

Brandon

**Comment by AndrewLJackson** [comment]
Sorry, my fault. Attached



--
Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by bsharris381** [comment]
Andrew,

I’m new to GitHub…I think that I was not looking in the correct place for attachments.

THANKS!  Code worked fine on my end.  You saved me a lot of time.


Thank you for your time!

I will close out the issue.

Brandon
