### ISSUE TITLE
SIBER density plot shows different results if I add or remove groups.

### ISSUE THREAD

**Issue by Edward-Doherty** [AndrewLJackson/SIBER#61]
Hey Andrew,

I hope you are well and staying safe. I came across a peculiar issue recently that I have spent the last few days trying to fix. I am comparing niche size between 3 species and between 2 time periods. However, the results from the density plot for a given species changes depending on the number of grouping variables (i.e. species) I have. I have attached a Word doc for more info. Would you mind taking a look when you have a chance?

Best wishes,
Edward Doherty
PhD Student
University of Liverpool
edward.doherty@liverpool.ac.uk

[Issue with SIBER.docx](https://github.com/AndrewLJackson/SIBER/files/4598708/Issue.with.SIBER.docx)

**Comment by AndrewLJackson** [comment]
﻿Hi Edward

Are you absolutely sure your sub-setting and labelling is working as you expect? You could check the scatter plots manually and/or generate some summary statistics outside of SIBER.

The models in SIBER are actually fitted separately to each sub-group so they should be almost identical give or take MCMC sampling error.

If after that there really does seem to be a problem could you email me directly your data and code and I will take a look jacksoan@tcd.ie<mailto:jacksoan@tcd.ie>

Best wishes

Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by Edward-Doherty** [comment]
Dear Andrew,

Thank you for your response. After double checking my code, labels and sub-setting, the problem still persists. I also tried changing my labels to numbers (see ‘group’ and ‘community’ columns in the data) to see if that had an effect, but it did not. The SEAs match between the two metrics tables, but as soon as I run the model, the posterior modes and confidence intervals diverge (see summary stats at the bottom of sheet). I have attached my data and code for you to check out, but I understand you’re probably very busy so please only do so when it’s convenient.

Many thanks,
Ed



P.S. I have CC’d in my supervisor, Rachel Jeffreys, to keep her in the loop.

**Comment by AndrewLJackson** [comment]
hi Edward

im not seeing the code and data. could you resend. if you don't want to post them publicly email me directly
best wishes
Andrew

**Comment by AndrewLJackson** [comment]
bug found and fixed in most recent update.
