### ISSUE TITLE
siberKapow vignette

### ISSUE THREAD

**Issue by hwellar** [AndrewLJackson/SIBER#70]
Hello, 
Is there an explanatory vignette for siberKapow? Sheppard et al. 2018 states there is one, but I have not found one that specifically shows you how to generate the boundary plot or the total area. 

I would like to calculate the proportion each species niche area represents of the total area. I currently do this by summing the SEAb modes of all species(groups) and then dividing each individual species SEAb mode by the sum for all species. However, it seems it may be better to use SIBER kapow to do this. However it is unclear to me how to use the output from siberKapow to generate the total area? 

Any thoughts or help on this would be greatly appreciated. Thank you in advance.

**Comment by AndrewLJackson** [comment]
hi. sorry for the delay. 

I have located and updated SIBER to now include the vignette. This can be accessed by installing the latest development version of SIBER via 

```
  # install.packages("devtools") # install if necessary
  devtools::install_github("andrewljackson/SIBER@master",
  build_vignettes = TRUE)
  library(SIBER)
```
