### ISSUE TITLE
remove data points and keep ellipses

### ISSUE THREAD

**Issue by eapollardd** [AndrewLJackson/SIBER#73]
Hi all,

Is there an easy way to display only ellipses and hull lines and hide individual data points?

plotSiberObject(siber.example,
                ax.pad = 1, 
                hulls = F, community.hulls.args, 
                ellipses = T, group.ellipses.args,
                group.hulls = T, group.hull.args,
                bty = "L",
                iso.order = c(1,2),
                xlab = expression({delta}^13*C~'\u2030'),
                ylab = expression({delta}^15*N~'\u2030'))

Thanks so much!

Erica

**Comment by AndrewLJackson** [comment]
Hi Erica

No is the short answer. You will have to build a custom plot. There is a ggplot example in the vignettes

Best wishes
Andrew



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | ***@***.******@***.***>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 15 Apr 2021, at 21:56, eapollardd ***@***.***> wrote:

﻿

Hi all,

Is there an easy way to display only ellipses and hull lines and hide individual data points?

plotSiberObject(siber.example,
ax.pad = 1,
hulls = F, community.hulls.args,
ellipses = T, group.ellipses.args,
group.hulls = T, group.hull.args,
bty = "L",
iso.order = c(1,2),
xlab = expression({delta}^13C~'\u2030'),
ylab = expression({delta}^15N~'\u2030'))

Thanks so much!

Erica

**Comment by eapollardd** [comment]
No worries. Thanks for such a quick response! I have already started fiddling with the ggplot vignettes. 

Thanks,
Erica
