### ISSUE TITLE
Negative Bayesian overlap values

### ISSUE THREAD

**Issue by Davide-Cicala** [AndrewLJackson/SIBER#74]
Hi all,
if i have no overlap among ellipses why when run:
bayes.overlap.G1.G2 <- bayesianOverlap("1.1", "1.2", ellipses.posterior, 
                                       draws = 2, p.interval = 0.95,
                                       n = 360)
i find a negative values of bayesian overlap among these?

Thanks in advances.

**Comment by AndrewLJackson** [comment]
Hi Davide
I would need to see some plots of the data please.

Best wishes
Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | ***@***.******@***.***>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

From: Davide-Cicala ***@***.***>
Date: Friday, 21 May 2021 at 07:53
To: AndrewLJackson/SIBER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AndrewLJackson/SIBER] Negative Bayesian overlap values (#74)

Hi all,
if i have no overlap among ellipses why when run:
bayes.overlap.G1.G2 <- bayesianOverlap("1.1", "1.2", ellipses.posterior,
draws = 2, p.interval = 0.95,
n = 360)
i find a negative values of bayesian overlap among these?

Thanks in advances.

**Comment by Davide-Cicala** [comment]
Hi Andrew,
here the ellipses 
[ELL.INV.sp copia.pdf](https://github.com/AndrewLJackson/SIBER/files/6521189/ELL.INV.sp.copia.pdf)

**Comment by Davide-Cicala** [comment]
Hi Andrew,
which plots do you need to see?
I can produce and send it.

Thanks,

Best wishes

Davide.

**Comment by AndrewLJackson** [comment]
﻿hi Davide

Could you send me please the raw data and script file that reproduces your negative areas for these two groups only please?

bayes.overlap.G1.G2 <- bayesianOverlap("1.1", "1.2", ellipses.posterior,
draws = 2, p.interval = 0.95,
n = 360)


Best wishes

Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | ***@***.******@***.***>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

From: Davide-Cicala ***@***.***>
Date: Wednesday, 26 May 2021 at 19:08
To: AndrewLJackson/SIBER ***@***.***>
Cc: Andrew Jackson ***@***.***>, Comment ***@***.***>
Subject: Re: [AndrewLJackson/SIBER] Negative Bayesian overlap values (#74)
Hi Andrew,
which plots do you need to see?
I can produce and send it.

Thanks,

Best wishes

Davide.

**Comment by Davide-Cicala** [comment]
Hi Andrew,
Sure, files are attached.
They contains the 2 couples that didn’t overlap but showed negative overlap, (Ameiurus Vs Leuciscus; Anguilla Vs Esox).

Thanks.

best,

Davide

**Comment by Davide-Cicala** [comment]
[Dataset DC.xlsx](https://github.com/AndrewLJackson/SIBER/files/6555023/Dataset.DC.xlsx)

**Comment by Davide-Cicala** [comment]
Unfortunately this page don't upload the file version of the R script.
I just sent in your work e-mail.
Thanks,
Davide.

**Comment by Davide-Cicala** [comment]
Hi Andrew
Sorry, have you received the mail conteining the data and R script?

Best wishes,

Davide.
