### ISSUE TITLE
How can I reorder groups in the output of siberDensityplot?

### ISSUE THREAD

**Issue by ekhaque** [AndrewLJackson/SIBER#83]
![image](https://user-images.githubusercontent.com/101710489/158571516-be5c5fc3-22ad-4dbb-a699-a1565e8006dc.png)

I would like to reorder the groups in the plot? how can I do it?

**Comment by AndrewLJackson** [comment]
yes, you can reorder the plot by changing the index for the columns.

so if you have a data frame called my_df which has say 6 columns, you can change the order by

siberDensityPlot(my_df[, c(3, 1, 6, 2, 4, 5)])

you will have to change the labels manually too so be careful
