### ISSUE TITLE
Why are TA and SD not being calculated for community metrics?

### ISSUE THREAD

**Issue by naalipalo** [AndrewLJackson/SIBER#86]
Ive just run my script and tried to calculate the community metrics and am getting 0s for TA and the SDNND.  I used the 
`mu.post <- extractPosteriorMeans(siber.claw, ellipses.posterior)
layman.B <- bayesianLayman(mu.post)`

This produces a list of my 3 communities and this is just an example of the head of one of the lists:
`         dY_range dX_range TA CD    NND SDNND`
` [1,] 0.90859931 4.425017e-01  0 0.50531191 1.01062381     0`
`[2,] 1.00431386 5.884000e-02  0 0.50301801 1.00603603     0`
` [3,] 1.04400555 2.539059e-01  0 0.53721872 1.07443744     0`
   `[4,] 1.38595055 1.522896e-02  0 0.69301711 1.38603422     0`
   `[5,] 1.03039552 3.503071e-01  0 0.54415761 1.08831522     0`
   `[6,] 0.68122125 1.980484e-01  0 0.35471311 0.70942621     0`
   `[7,] 1.22335820 2.668896e-02  0 0.61182465 1.22364929     0`

Ive tried:
`community.ML <- communityMetricsML(siber.claw) `
`                    tip             mid              base`
`dY_range 1.0856836 1.330689189 1.20906677`
`dX_range 0.1002440 0.004752782 0.09804213`
`TA            0.0000000 0.000000000 0.00000000`
`CD           0.5451509 0.665348838 0.60651767`
`MNND     1.0903017 1.330697677 1.21303533`
`SDNND    0.0000000 0.000000000 0.00000000`

When I did just the basic `laymanMetrics(claw2$iso1, claw2$iso2)` NOT on a siber object, I get values, but I don't know why they aren't being calculated off the siber object. Any reason why I don't get it in the `community.ML` command?

Following Layman et al 2007, my collaborators suggested we I look at the MNND and SDNND by groups within my communities and see if there is a statistical difference. I wouldn't quite know how to do that, or if its necessary. Any suggestions?

**Comment by naalipalo** [comment]
I just read on the first page that TA in the community metric's will be 0's if you have <3 groups.  I have 2 groups. So, my follow up question would be can I just swap my groups and communities then? So, id have 3 groups and 2 communities.

**Comment by AndrewLJackson** [comment]
﻿Hi

If you are getting zero for TA it suggests you have less than two groups per community and so the area of the line that links the centroids of both groups is zero. You need at least 3 centroids to get an area.

Follow the intro to SIBER vignette. You cant calculate Bayesian “layman metrics” on single groups of data for reasons articulated in the JAE paper that describes SIBER.

Best wishes
Andrew





--

Dr Andrew Jackson, PhD, FTCD
Director Biology and Biomedical Sciences degree TR060
Associate Professor - Zoology
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

***@***.***
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

From: naalipalo ***@***.***>
Date: Wednesday, 30 March 2022 at 23:15
To: AndrewLJackson/SIBER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AndrewLJackson/SIBER] TA and SD not being calculated for community metrics (Issue #86)

Ive just run my script and tried to calculate the community metrics and am getting 0s for TA and the SDNND. I used the
mu.post <- extractPosteriorMeans(siber.claw, ellipses.posterior) layman.B <- bayesianLayman(mu.post)

This produces a list of my 3 communities and this is just an example of the head of one of the lists:
dY_range dX_range TA CD NND SDNND
[1,] 0.90859931 4.425017e-01 0 0.50531191 1.01062381 0
[2,] 1.00431386 5.884000e-02 0 0.50301801 1.00603603 0
[3,] 1.04400555 2.539059e-01 0 0.53721872 1.07443744 0
[4,] 1.38595055 1.522896e-02 0 0.69301711 1.38603422 0
[5,] 1.03039552 3.503071e-01 0 0.54415761 1.08831522 0
[6,] 0.68122125 1.980484e-01 0 0.35471311 0.70942621 0
[7,] 1.22335820 2.668896e-02 0 0.61182465 1.22364929 0

Ive tried:
community.ML <- communityMetricsML(siber.claw)
tip mid base
dY_range 1.0856836 1.330689189 1.20906677
dX_range 0.1002440 0.004752782 0.09804213
TA 0.0000000 0.000000000 0.00000000
CD 0.5451509 0.665348838 0.60651767
MNND 1.0903017 1.330697677 1.21303533
SDNND 0.0000000 0.000000000 0.00000000

When I did just the basic laymanMetrics(claw2$iso1, claw2$iso2) NOT on a siber object, I get values, but I don't know why they aren't being calculated off the siber object. Any reason why I don't get it in the community.ML command?

Following Layman et al 2007, my collaborators suggested we I look at the MNND and SDNND by groups within my communities and see if there is a statistical difference. I wouldn't quite know how to do that, or if its necessary. Any suggestions?

**Comment by AndrewLJackson** [comment]
﻿you can define your groups and communities anyway that makes sense for you and your data.

--

Dr Andrew Jackson, PhD, FTCD
Director Biology and Biomedical Sciences degree TR060
Associate Professor - Zoology
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

***@***.***
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

From: naalipalo ***@***.***>
Date: Wednesday, 30 March 2022 at 23:43
To: AndrewLJackson/SIBER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [AndrewLJackson/SIBER] Why are TA and SD not being calculated for community metrics? (Issue #86)

I just read on the first page that TA in the community metric's will be 0's if you have <3 groups. I have 2 groups. So, my follow up question would be can I just swap my groups and communities then? So, id have 3 groups and 2 communities.
