### ISSUE TITLE
siber.example <- createSiberObject(my data) sample size n<5 Warning message

### ISSUE THREAD

**Issue by elvitaeglite** [AndrewLJackson/SIBER#88]
Hi Andrew,

I am applying SIBER to a small sample size. Mostly less than 10 samples, but in some cases less than R. 

When I run siber.example <- createSiberObject(my datat) - I receive this message ' At least one of your groups has less than 5 observations.
          The absolute minimum sample size for each group is 3 in order
          for the various ellipses and corresponding metrics to be
          calculated. More reasonably though, a minimum of 5 data points
          are required to calculate the two means and the 2x2 covariance
          matrix and not run out of degrees of freedom. Check the item
          named ‘sample.sizes’ in the object returned by this function
          in order to locate the offending group. Bear in mind that NAs in
          the sample.size matrix simply indicate groups that are not
          present in that community, and is an acceptable data structure
          for these analyses.'

Can you please suggest me how to proceed with it?
Thanks, Elvita

**Comment by AndrewLJackson** [comment]
you _can_ still proceed, but how much trust you can put in your estimated statistics is highly questionable. At the very least the uncertainties will be so huge as to render any comparison with those groups impossible or non-significant. More data in those groups is the only real solution if you want to proceed with this type of analysis.
