### ISSUE TITLE
AXES LIMITS

### ISSUE THREAD

**Issue by IlseBarraza** [AndrewLJackson/SIBER#90]
Hi everyone,
I was wondering if is it possible to write a limit on the axes, this because I'm going to compare graphics and I have to modify theirs axes in order to have the same x and y limits.

I hope someone could help me.

**Comment by AndrewLJackson** [comment]
If you want to customise plots beyond the rather basic ones included in SIBER you will need to build them using your own code. I suggest ggplot and the SIBER vignette "Plot-SIA-ggplot2" for the raw data and then the vignettes on comparing populations and communities for examples on how to plot the posterior distributions.
