### ISSUE TITLE
Ellipse outsizing convex hull when plotting 95% of the data - are ellipse estimates at the .95 p interval are frequently bigger than the convex hulls?

### ISSUE THREAD

**Issue by addielynne** [AndrewLJackson/SIBER#94]
Hi all,

I'm having a strange thing happen with some of my data at the .95 p interval. The ellipse when 95% of the data is plotted suddenly gets huge and is way bigger than the convex hull, which is not what I am used to seeing. I am wondering if ellipse estimates at the .95 p interval are frequently bigger than the convex hulls? Things look pretty normal at the 50-85% range, but then the problem emerges at 95%. Photos of the 0.75, 0.85, and 0.95 p interval attached. Any information much appreciated!

![thumbnail_image](https://user-images.githubusercontent.com/116296369/219797094-64aa40d6-418f-49dc-8176-21ccb937c37a.png)
![thumbnail_image](https://user-images.githubusercontent.com/116296369/219797121-40c9dc47-da27-4cde-af51-2fbc2d11cb39.png)
![thumbnail_image](https://user-images.githubusercontent.com/116296369/219797136-06bf737b-d453-40dc-a92a-6177c1d7ca33.png)

**Comment by AndrewLJackson** [comment]
There is a vignette "Points inside or Outside Ellipse" included in the package that attempts to test for this and has some additional explanation. That code might give you a starting point if you want to develop further tests. But you can see that, for smaller sample sizes, there is a tendency for the ellipse to contain more than 95% of the data.
